### ISSUE TITLE
[v2] Multiselect prompt error when specifying a skip function

### ISSUE THREAD

**Issue by brpaz** [egoist/sao#165]
Hello.

I have the following prompt in my saofile that I only want to execute, based on the result of another prompt. 

```js
 {
        type: 'multiselect',
        name: 'dependabotEcosystem',
        message: 'Dependabot Ecosystem',
        choices: [
          {
            message: 'NodeJS',
            name: 'dep_node',
            checked: false
          }
        ],
        skip: ({ answers }) => {
          return !answers.git_files.includes('dependabot');
        }
      },
```

In Sao V1, that could be done with the `when` function. I discovered that with enquirer,  I need to use the `skip` function.

But when I use the skip function together, with a multiselect prompt it gives the following error:

```
(node:109253) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at MultiSelect.filter (/home/bruno/.npm-global/lib/node_modules/sao/dist/chunk.4DEZzoSo.js:2056:28)
    at MultiSelect.get enabled [as enabled] (/home/bruno/.npm-global/lib/node_modules/sao/dist/chunk.4DEZzoSo.js:2153:19)
    at MultiSelect.get selected [as selected] (/home/bruno/.npm-global/lib/node_modules/sao/dist/chunk.4DEZzoSo.js:2166:35)
    at MultiSelect.submit (/home/bruno/.npm-global/lib/node_modules/sao/dist/chunk.4DEZzoSo.js:2090:24)
    at /home/bruno/.npm-global/lib/node_modules/sao/dist/chunk.4DEZzoSo.js:1332:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:109253) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:109253) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the futur
```

It works fine for other prompt types, like autocomplete.

I tested directly with Enquirer, and it works, so I guess it should be same issue with SAO.

I am using SAO V2 beta 1.

**Comment by egoist** [comment]
Can you give me a full example? cuz the code you provided seems to work fine for me

**Comment by brpaz** [comment]
I eventually got it resolved. Not remember exactly what the problem was. (a typo somewhere or something like that)-

So I will close this as in was not an issue with sao directly.
