### ISSUE TITLE
Can't resolve local path.

### ISSUE THREAD

**Issue by gluons** [egoist/sao#34]
I've created [my personal template](https://github.com/gluons/template-gluons).

I required some file by local path.
```javascript
const utils = require('./lib/utils');
```

I got this error when I try to use it myself.

```bash
> sao gluons test         
ERROR Error: Cannot find module './lib/utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/illuminator/.nvm/versions/node/v6.10.3/lib/node_modules/template-gluons/sao.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by egoist** [comment]
Hmm, you didn't publish `lib` folder on npm, check https://github.com/gluons/template-gluons/blob/master/package.json#L7-L10

**Comment by gluons** [comment]
Oh!!! I forget to edit default `package.json`. 🤢
Sorry for stupid issue. 🤕

**Comment by egoist** [comment]
Never mind, happy generating 😎
